import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir } from 'node:fs/promises';
import { plusDays,today } from '../../lib/pricing';
import { randomBytes,randomUUID } from 'node:crypto';
const origin='http://localhost:3000';
test.beforeEach(async()=>{await mkdir('artifacts',{recursive:true});});
test('desktop experience: photographs, map, two-cabin comparison and accessibility',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');await page.evaluate(()=>document.fonts.ready);await expect(page.getByRole('heading',{level:1})).toContainText('A little closer');
  await page.locator('.hero-photo').evaluate((image:HTMLImageElement)=>image.decode()).catch(()=>{});
  await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Explore Cove on the property map'}).click();await expect(page.locator('.map-cabin h3')).toHaveText('Cove');
  await page.locator('.cabin-card').filter({has:page.getByRole('heading',{name:'Salt',exact:true})}).getByRole('button',{name:'Compare Salt',exact:true}).click();
  await page.locator('.cabin-card').filter({has:page.getByRole('heading',{name:'Cove',exact:true})}).getByRole('button',{name:'Compare Cove',exact:true}).click();
  await page.locator('.compare-tray').getByRole('button',{name:'Compare',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.compare-columns article')).toHaveCount(2);await page.screenshot({path:'artifacts/compare-desktop.png'});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);expect(errors).toEqual([]);
});
test('mobile layout: navigation, reduced motion and no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.evaluate(()=>document.fonts.ready);await expect(page.getByRole('button',{name:'Open navigation'})).toBeVisible();await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.locator('#mobile-navigation')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#mobile-navigation')).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
  await page.goto('/cabins/cove/');await expect(page.getByRole('heading',{level:1})).toContainText('Cove');await expect(page.getByRole('img',{name:/Cove concept floor plan/})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'artifacts/cabin-mobile.png',fullPage:true});
});
test('complete booking: extras, confirmation, changed availability and cancellation',async({page,request})=>{
  const start=plusDays(today(),85),end=plusDays(today(),88);
  await page.goto(`/stay/?cabin=cove&checkIn=${start}&checkOut=${end}&guests=4`);await expect(page.getByRole('button',{name:'Choose Cove',exact:true})).toBeEnabled();
  await page.getByRole('checkbox',{name:'Breakfast at your door',exact:true}).check();await page.getByRole('checkbox',{name:'Your private sauna hour',exact:true}).check();await page.getByLabel('Your full name',{exact:true}).fill('Portfolio Test Guest');await page.getByLabel('Email for your stay',{exact:true}).fill('portfolio@example.test');await page.getByRole('checkbox',{name:/I have read the booking and cancellation terms/}).check();
  await expect(page.getByRole('button',{name:'Continue to test payment'})).toBeEnabled();await page.screenshot({path:'artifacts/booking-desktop.png',fullPage:true});await page.getByRole('button',{name:'Continue to test payment'}).click();await expect(page.getByRole('button',{name:'Approve test payment'})).toBeVisible();await page.getByRole('button',{name:'Approve test payment'}).click();await expect(page.getByRole('heading',{level:1})).toHaveText('We’ll keep a little quiet for you.');await page.screenshot({path:'artifacts/confirmation-desktop.png',fullPage:true});
  const calendar=await request.get('/api/calendar/cove');expect((await calendar.json()).some((r:{start:string;end:string})=>r.start===start&&r.end===end)).toBe(true);
  await page.getByRole('button',{name:'Cancel this stay',exact:true}).click();await page.getByRole('button',{name:'Confirm cancellation',exact:true}).click();await expect(page.getByRole('heading',{level:1})).toHaveText('Until another time.');expect((await (await request.get('/api/calendar/cove')).json()).some((r:{start:string})=>r.start===start)).toBe(false);
});
test('failed payment remains unconfirmed and the dates are available again',async({page,request})=>{
  const checkIn=plusDays(today(),100),checkOut=plusDays(today(),103),accessToken=randomBytes(32).toString('hex');const input={cabinId:'pine',checkIn,checkOut,guests:2,addOns:[]};const quote=await (await request.post('/api/quote',{headers:{Origin:origin},data:input})).json();const created=await request.post('/api/reservations',{headers:{Origin:origin},data:{...input,name:'Failure Test Guest',email:'failure@example.test',idempotencyKey:randomUUID(),accessToken,expectedTotal:quote.total}});expect(created.status()).toBe(201);const {id}=await created.json();await page.goto(`/booking/?id=${id}#access=${accessToken}`);await page.getByRole('button',{name:'Simulate payment failure'}).click();await expect(page.getByRole('heading',{level:1})).toHaveText('Payment wasn’t completed.');await expect(page.getByText('NO BOOKING WAS CONFIRMED',{exact:true})).toBeVisible();await page.screenshot({path:'artifacts/payment-failure.png',fullPage:true});const result=await request.post('/api/availability',{headers:{Origin:origin},data:{checkIn,checkOut,guests:2,addOns:[]}});expect((await result.json()).find((r:{cabinId:string})=>r.cabinId==='pine').available).toBe(true);
});
test('owner signs in, blocks dates, changes a rate and publishes safe content',async({page,request})=>{
  await page.goto('/admin/');await page.getByLabel('Owner passphrase',{exact:true}).fill(process.env.TEST_ADMIN_PASSWORD||'Tidehouse-test-only-password-2026');await page.getByRole('button',{name:'Open dashboard'}).click();await expect(page.getByRole('heading',{level:1})).toHaveText('Behind the quiet.');await page.screenshot({path:'artifacts/owner-dashboard.png',fullPage:true});
  await page.getByRole('button',{name:'Availability',exact:true}).click();await page.getByLabel('Cabin',{exact:true}).selectOption('dune');const start=plusDays(today(),160),end=plusDays(today(),163);await page.getByLabel('From',{exact:true}).fill(start);await page.getByLabel('Until (exclusive)',{exact:true}).fill(end);await page.getByLabel('Owner note',{exact:true}).fill('Test maintenance window');await page.getByRole('button',{name:'Block these dates'}).click();await expect(page.getByRole('status')).toContainText('Dates blocked');const result=await request.post('/api/availability',{headers:{Origin:origin},data:{checkIn:start,checkOut:end,guests:2,addOns:[]}});expect((await result.json()).find((r:{cabinId:string})=>r.cabinId==='dune').available).toBe(false);
  await page.getByRole('button',{name:'Rates',exact:true}).click();await page.getByLabel('Amount per night (CAD)',{exact:true}).fill('301.25');await page.getByRole('button',{name:'Save rate',exact:true}).click();await expect(page.getByRole('status')).toContainText('Rate saved');
  await page.getByRole('button',{name:'Content',exact:true}).click();await page.getByLabel('Document',{exact:true}).selectOption('arrival');await page.getByLabel('Title',{exact:true}).fill('Your arrival, calmly arranged.');await page.getByLabel('Body text',{exact:true}).fill('This is an edited arrival note. <script>window.hacked=true</script>\n\nCheck-in remains from 16:00. Test content is safely rendered as text.');await page.getByRole('button',{name:'Publish changes',exact:true}).click();await expect(page.getByRole('status')).toContainText('Content published');await page.goto('/arrival/');await expect(page.getByRole('heading',{level:1})).toHaveText('Your arrival, calmly arranged.');expect(await page.evaluate(()=>Boolean((window as Window&{hacked?:boolean}).hacked))).toBe(false);
});
