import {test,expect,type APIRequestContext,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {today,addDays} from '../../lib/domain';
const origin='http://localhost:3000';
const send=(request:APIRequestContext,path:string,data:unknown,token?:string)=>request.post(`/api/${path}`,{data,headers:{Origin:origin,...(token?{Authorization:`Bearer ${token}`}:{})}});
async function ready(page:Page){await page.evaluate(()=>document.fonts.ready);}
async function snapshot(page:Page,name:string){mkdirSync('evidence',{recursive:true});await ready(page);await page.screenshot({path:`evidence/${name}.png`,fullPage:true});}
function offset(project:string,base:number){return base+(project==='mobile'?20:0);}
test('editorial homepage, five cabins, map and responsive layout',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('doing nothing.');await expect(page.locator('.cabin-card')).toHaveCount(5);await page.getByRole('button',{name:'Explore Driftwood',exact:true}).click();await expect(page.locator('.map-cabin-preview h3')).toHaveText('Driftwood');
 await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=650){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,90));}window.scrollTo(0,0);});
 await expect.poll(()=>page.locator('img').evaluateAll(images=>images.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0)),{timeout:25000}).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);await snapshot(page,`home-${info.project.name}`);expect(errors).toEqual([]);
});
test('compare two cabins, inspect floor plan and choose a cabin',async({page},info)=>{
 await page.goto(`/stay?arrival=${addDays(today(),offset(info.project.name,180))}&departure=${addDays(today(),offset(info.project.name,183))}`);await page.getByRole('checkbox',{name:'Compare The Lookout',exact:true}).check();await page.getByRole('checkbox',{name:'Compare Driftwood',exact:true}).check();await page.getByRole('button',{name:'Compare cabins (2/2)'}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog')).toContainText('900 mm');await page.getByRole('button',{name:'Choose Driftwood'}).click();await expect(page.locator('.selected-cabin-title h2')).toHaveText('Driftwood');await page.locator('summary').filter({hasText:'The floor plan'}).click();await expect(page.getByRole('img',{name:/Driftwood illustrative floor plan/})).toBeVisible();await snapshot(page,`stay-${info.project.name}`);
});
test('complete booking, addons, approval, receipt and cancellation',async({page,request},info)=>{
 const arrival=addDays(today(),offset(info.project.name,210)),departure=addDays(arrival,3);await page.goto(`/stay?cabin=1&arrival=${arrival}&departure=${departure}&guests=2`);await page.getByRole('checkbox',{name:/Slow-morning breakfast/}).check();await page.getByRole('checkbox',{name:/The wood-fired sauna/}).check();await expect(page.getByRole('button',{name:'Continue to your details'})).toBeEnabled();await page.getByRole('button',{name:'Continue to your details'}).click();await page.getByLabel('Your name',{exact:true}).fill('Portfolio Guest');await page.getByLabel('Email address',{exact:true}).fill('guest@example.test');await page.getByRole('checkbox',{name:/I have read the/}).check();await page.getByRole('button',{name:'Continue to test payment'}).click();await expect(page).toHaveURL(/\/booking\/[a-f0-9-]+/);await expect(page.getByRole('heading',{name:'A little quiet, on hold.'})).toBeVisible();await page.getByRole('button',{name:'Simulate approved payment'}).click();await expect(page.getByRole('heading',{name:'Your quieter days are booked.'})).toBeVisible();const occupied=await(await request.get(`/api/availability?from=${arrival}&to=${departure}`)).json();expect(occupied.occupied.some((r:{cabin_id:number})=>r.cabin_id===1)).toBe(true);await snapshot(page,`confirmation-${info.project.name}`);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download your receipt'}).click();expect((await download).suggestedFilename()).toMatch(/^TIDEHOUSE-.*\.txt$/);await page.getByRole('button',{name:'Cancel this reservation'}).click();await page.getByRole('button',{name:'Confirm cancellation'}).click();await expect(page.getByRole('heading',{name:'Your stay has been cancelled.'})).toBeVisible();await expect(page.getByText('Refund refunded',{exact:true})).toBeVisible();
});
test('declined payment leaves no confirmation and releases dates',async({page,request},info)=>{
 const selection={cabinId:3,arrival:addDays(today(),offset(info.project.name,250)),departure:addDays(today(),offset(info.project.name,253)),guests:4,addons:[]};const quote=await(await send(request,'quote',selection)).json();const reserved=await(await send(request,'bookings',{selection,name:'Decline Test',email:'decline@example.test',acceptedPolicy:true,expectedTotal:quote.quote.total,idempotencyKey:randomUUID()})).json();await page.goto(reserved.url);await page.getByRole('button',{name:'Simulate declined payment'}).click();await expect(page.getByRole('heading',{name:'The payment wasn’t approved.'})).toBeVisible();expect((await(await send(request,'quote',selection)).json()).available).toBe(true);const state=await(await request.get(`/api/bookings/${reserved.id}`,{headers:{Authorization:`Bearer ${reserved.token}`}})).json();expect(state.status).toBe('failed');expect(state.paid_at).toBeNull();
});
test('two visitor requests cannot both confirm the same cabin',async({request},info)=>{
 const selection={cabinId:2,arrival:addDays(today(),offset(info.project.name,280)),departure:addDays(today(),offset(info.project.name,283)),guests:2,addons:[]},q=await(await send(request,'quote',selection)).json();const body={selection,name:'Race Guest',email:'race@example.test',acceptedPolicy:true,expectedTotal:q.quote.total};const attempts=await Promise.all([send(request,'bookings',{...body,idempotencyKey:randomUUID()}),send(request,'bookings',{...body,email:'other@example.test',idempotencyKey:randomUUID()})]);expect(attempts.map(r=>r.status()).sort()).toEqual([201,409]);const winner=await attempts.find(r=>r.status()===201)!.json();expect((await send(request,`bookings/${winner.id}/simulate`,{outcome:'paid'},winner.token)).ok()).toBe(true);expect((await send(request,'bookings',{...body,idempotencyKey:randomUUID()})).status()).toBe(409);
});
test('owner login, blocks, rates and content publishing',async({page,request},info)=>{
 await page.goto('/studio');await page.getByLabel('Owner password',{exact:true}).fill(process.env.E2E_ADMIN_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Block these dates'})).toBeVisible();const arrival=addDays(today(),offset(info.project.name,100)),departure=addDays(arrival,3);await page.getByLabel('Cabin',{exact:true}).selectOption('5');await page.getByLabel('From',{exact:true}).fill(arrival);await page.getByLabel('Until (checkout date)',{exact:true}).fill(departure);await page.getByRole('button',{name:'Block these dates'}).click();await expect(page.getByRole('status')).toContainText('Dates blocked');const quote=await(await send(request,'quote',{cabinId:5,arrival,departure,guests:2,addons:[]})).json();expect(quote.available).toBe(false);await snapshot(page,`studio-${info.project.name}`);await page.getByRole('button',{name:'Rates',exact:true}).click();await page.getByLabel('Rate in CAD').fill('432.10');await page.getByRole('button',{name:'Save nightly rate'}).click();await expect(page.getByRole('status')).toContainText('Rates saved');const fresh=await(await send(request,'quote',{cabinId:5,arrival,departure,guests:2,addons:[]})).json();expect(fresh.quote.nights.every((n:{cents:number})=>n.cents===43210)).toBe(true);await page.getByRole('button',{name:'Editorial content'}).click();await page.getByLabel('Page title',{exact:true}).fill(`A quietly edited guide — ${info.project.name}`);await page.getByRole('button',{name:'Publish this page'}).click();await expect(page.getByRole('status')).toContainText('Editorial page published');await page.goto('/field-notes/guide');await expect(page.getByRole('heading',{level:1})).toHaveText(`A quietly edited guide — ${info.project.name}`);
});
test('public callers cannot use owner actions or private booking data',async({request})=>{expect((await request.get('/api/admin/state')).status()).toBe(401);expect((await send(request,'admin/blocks',{cabinId:1})).status()).toBe(401);expect((await request.post('/api/quote',{data:{}})).status()).toBe(403);expect((await request.get(`/api/bookings/${randomUUID()}`)).status()).toBe(401);expect((await request.post('/api/webhooks/stripe',{data:{}})).status()).not.toBe(200);});
test('homepage and booking page pass automated WCAG A/AA',async({page},info)=>{
 for(const path of ['/',`/stay?arrival=${addDays(today(),offset(info.project.name,320))}&departure=${addDays(today(),offset(info.project.name,323))}`]){await page.goto(path);await ready(page);if(path!=='/')await expect(page.getByRole('button',{name:'Continue to your details'})).toBeEnabled();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,description:v.description,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
});
