import test,{before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { Server } from 'node:http';
import { app } from '../server/app';
import { pool } from '../server/db';
import { migrate } from '../server/migrate';
import { config } from '../server/config';
import { hash,secureToken } from '../server/security';
import { reserve,authorizeBooking,simulatePayment,cancelBooking,settleEvent,calendar,quoteStay,reconcileHolds } from '../server/booking-service';
import { processOutbox } from '../server/outbox';
import { requireStripe } from '../server/payments';
import { buildQuote,plusDays,today } from '../lib/pricing';
import { cabins } from '../lib/catalog';
import type { ReservationRequest } from '../lib/types';
let server:Server;let url='';
function input(offset=30,override:Partial<ReservationRequest>={}):ReservationRequest{const s={cabinId:'salt' as const,checkIn:plusDays(today(),offset),checkOut:plusDays(today(),offset+3),guests:2,addOns:[] as ('breakfast'|'sauna')[],name:'Test Guest',email:'guest@example.test',idempotencyKey:randomUUID(),accessToken:secureToken(),...override};return {...s,expectedTotal:override.expectedTotal??buildQuote(s).total};}
async function post(path:string,data:unknown,token?:string,cookie?:string){return fetch(url+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:config.origin,...(token?{Authorization:`Bearer ${token}`} :{}),...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)});}
async function login(){const r=await post('/api/admin/login',{password:process.env.TEST_ADMIN_PASSWORD||'Tidehouse-test-only-password-2026'});assert.equal(r.status,200);return r.headers.get('set-cookie')!.split(';')[0];}
async function sessionFor(id:string,token:string){const row=await authorizeBooking(id,token);return {id:row.checkout_id!,payment_status:'paid',amount_total:row.total_cents,currency:'cad',metadata:{bookingId:id},payment_intent:`pi_sim_${id}`,livemode:false};}
before(async()=>{await migrate();server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('No test server address.');url=`http://127.0.0.1:${address.port}`;});
beforeEach(async()=>{await pool.query('TRUNCATE reservations,payment_events,outbox,admin_sessions,rate_limits,audit_log RESTART IDENTITY CASCADE');await pool.query('DELETE FROM rates');for(const c of cabins)await pool.query('UPDATE cabins SET base_rate=$2,version=1 WHERE id=$1',[c.id,c.baseRate]);});
after(async()=>{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await pool.end();});
test('PostgreSQL exclusion constraint is installed',async()=>{const r=await pool.query("SELECT contype FROM pg_constraint WHERE conname='no_overlapping_inventory'");assert.equal(r.rows[0].contype,'x');});
test('20 simultaneous visitors produce exactly one inventory hold',async()=>{const responses=await Promise.all(Array.from({length:20},()=>post('/api/reservations',input())));assert.equal(responses.filter(r=>r.status===201).length,1);assert.equal(responses.filter(r=>r.status===409).length,19);const count=await pool.query("SELECT count(*)::int AS n FROM reservations WHERE status='holding'");assert.equal(count.rows[0].n,1);});
test('database itself rejects overlapping writes even when application checks are bypassed',async()=>{const start=plusDays(today(),40),end=plusDays(today(),44);const results=await Promise.allSettled(Array.from({length:10},()=>pool.query("INSERT INTO reservations(id,cabin_id,start_date,end_date,guests,kind,status,provider,hold_expires_at) VALUES($1,'dune',$2,$3,0,'block','blocked','simulated',now())",[randomUUID(),start,end])));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);for(const r of results)if(r.status==='rejected')assert.equal(r.reason.code,'23P01');});
test('back-to-back stays and distinct cabins can be held concurrently',async()=>{const a=input();const b=input(33);const c=input(30,{cabinId:'cove',guests:4});const results=await Promise.all([reserve(a),reserve(b),reserve(c)]);assert.equal(new Set(results.map(r=>r.id)).size,3);});
test('identical checkout retries return the same reservation',async()=>{const i=input();const [a,b]=await Promise.all([reserve(i),reserve(i)]);assert.equal(a.id,b.id);const count=await pool.query('SELECT count(*)::int AS n FROM reservations');assert.equal(count.rows[0].n,1);});
test('an idempotency key cannot be reused for a changed request or access token',async()=>{const i=input();await reserve(i);await assert.rejects(reserve({...i,email:'other@example.test'}),{code:'IDEMPOTENCY_MISMATCH'});await assert.rejects(reserve({...i,accessToken:secureToken()}),{code:'IDEMPOTENCY_MISMATCH'});});
test('client price tampering is rejected before a hold is created',async()=>{const i=input();const r=await post('/api/reservations',{...i,expectedTotal:i.expectedTotal-100});assert.equal(r.status,409);assert.equal((await r.json()).code,'PRICE_CHANGED');assert.equal((await pool.query('SELECT count(*)::int AS n FROM reservations')).rows[0].n,0);});
test('capacity and malformed dates are validated on the server',async()=>{assert.equal((await post('/api/quote',{cabinId:'salt',checkIn:plusDays(today(),30),checkOut:plusDays(today(),33),guests:3,addOns:[]})).status,400);assert.equal((await post('/api/quote',{cabinId:'salt',checkIn:'2027-02-31',checkOut:'2027-03-04',guests:2,addOns:[]})).status,400);});
test('a failed payment never confirms the booking and releases its inventory',async()=>{const i=input();const b=await reserve(i);const failed=await simulatePayment(b.id,i.accessToken,'failed');assert.equal(failed.status,'failed');assert.equal((await calendar('salt')).length,0);assert.equal((await pool.query("SELECT count(*)::int AS n FROM reservations WHERE status='confirmed'")).rows[0].n,0);const retry=await reserve(input());assert.notEqual(retry.id,b.id);});
test('verified success confirms once, and duplicate events enqueue one confirmation',async()=>{const i=input();const b=await reserve(i);const s=await sessionFor(b.id,i.accessToken);await Promise.all([settleEvent('evt_same','checkout.session.completed',s),settleEvent('evt_same','checkout.session.completed',s)]);await settleEvent('evt_second','checkout.session.completed',s);assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'confirmed');assert.equal((await pool.query("SELECT count(*)::int AS n FROM outbox WHERE kind='confirmation'")).rows[0].n,1);});
test('a late expiration event cannot undo a paid reservation',async()=>{const i=input();const b=await reserve(i);await simulatePayment(b.id,i.accessToken,'paid');await settleEvent('evt_late_expire','checkout.session.expired',{...await sessionFor(b.id,i.accessToken),payment_status:'unpaid'});assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'confirmed');});
test('wrong payment amounts and currencies never fulfill',async()=>{const i=input();const b=await reserve(i);const s=await sessionFor(b.id,i.accessToken);await assert.rejects(settleEvent('evt_wrong_amount','checkout.session.completed',{...s,amount_total:1}));await assert.rejects(settleEvent('evt_wrong_currency','checkout.session.completed',{...s,currency:'usd'}));assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'holding');assert.equal((await pool.query('SELECT count(*)::int AS n FROM payment_events')).rows[0].n,0);});
test('live payment events and mismatched session IDs are rejected',async()=>{const i=input();const b=await reserve(i);const s=await sessionFor(b.id,i.accessToken);await assert.rejects(settleEvent('evt_live','checkout.session.completed',{...s,livemode:true}));await assert.rejects(settleEvent('evt_other','checkout.session.completed',{...s,id:'cs_other'}));assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'holding');});
test('expired local holds are released; they cannot later be simulated as paid',async()=>{const i=input();const b=await reserve(i);await pool.query("UPDATE reservations SET hold_expires_at=now()-interval '1 minute' WHERE id=$1",[b.id]);await reconcileHolds();assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'expired');await assert.rejects(simulatePayment(b.id,i.accessToken,'paid'));});
test('late payment on released inventory is refunded, never resurrected',async()=>{const i=input();const old=await reserve(i);await simulatePayment(old.id,i.accessToken,'failed');const replacement=await reserve(input());await settleEvent('evt_late_paid','checkout.session.completed',await sessionFor(old.id,i.accessToken));assert.equal((await authorizeBooking(old.id,i.accessToken)).status,'payment_conflict');assert.equal((await calendar('salt')).length,1);await processOutbox();const row=await authorizeBooking(old.id,i.accessToken);assert.equal(row.refunded_cents,row.total_cents);assert.equal((await pool.query('SELECT status FROM reservations WHERE id=$1',[replacement.id])).rows[0].status,'holding');});
test('pending cancellation is idempotent and frees the held dates',async()=>{const i=input();const b=await reserve(i);assert.equal((await cancelBooking(b.id,i.accessToken)).status,'cancelled');assert.equal((await cancelBooking(b.id,i.accessToken)).status,'cancelled');assert.equal((await calendar('salt')).length,0);});
test('early cancellation waits for an idempotent refund before releasing dates',async()=>{const i=input();const b=await reserve(i);await simulatePayment(b.id,i.accessToken,'paid');const cancelled=await cancelBooking(b.id,i.accessToken);assert.equal(cancelled.status,'cancelling');assert.equal(cancelled.refund_cents,i.expectedTotal);assert.equal((await calendar('salt')).length,1);await Promise.all([processOutbox(),processOutbox()]);const row=await authorizeBooking(b.id,i.accessToken);assert.equal(row.status,'cancelled');assert.equal(row.refunded_cents,i.expectedTotal);await cancelBooking(b.id,i.accessToken);assert.equal((await pool.query("SELECT count(*)::int AS n FROM outbox WHERE kind='refund'")).rows[0].n,1);assert.equal((await calendar('salt')).length,0);});
test('late cancellation applies the saved no-refund policy',async()=>{const i=input(2);const b=await reserve(i);await simulatePayment(b.id,i.accessToken,'paid');const cancelled=await cancelBooking(b.id,i.accessToken);assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.refund_cents,0);});
test('booking capability is required and secrets are not returned publicly',async()=>{const i=input();const b=await reserve(i);assert.equal((await fetch(`${url}/api/reservations/${b.id}`)).status,401);assert.equal((await fetch(`${url}/api/reservations/${b.id}`,{headers:{Authorization:`Bearer ${secureToken()}`}})).status,404);const r=await fetch(`${url}/api/reservations/${b.id}`,{headers:{Authorization:`Bearer ${i.accessToken}`}});const body=await r.json();assert.equal(body.token_hash,undefined);assert.equal(body.email,undefined);assert.equal(body.name,undefined);assert.equal(body.idempotency_key,undefined);});
test('cross-origin form writes and unprotected owner reads are denied',async()=>{assert.equal((await fetch(url+'/api/admin/overview')).status,401);const r=await fetch(url+'/api/reservations',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://attacker.example'},body:JSON.stringify(input())});assert.equal(r.status,403);});
test('owner blocks share the booking exclusion rule and cannot delete bookings',async()=>{const cookie=await login();const i=input();const b=await reserve(i);assert.equal((await post('/api/admin/blocks',{cabinId:'salt',start:i.checkIn,end:i.checkOut,note:'Maintenance'},undefined,cookie)).status,409);const block=await post('/api/admin/blocks',{cabinId:'dune',start:i.checkIn,end:i.checkOut,note:'Maintenance'},undefined,cookie);assert.equal(block.status,201);assert.equal((await post(`/api/admin/blocks/${b.id}/remove`,{},undefined,cookie)).status,404);const {id}=await block.json();assert.equal((await post(`/api/admin/blocks/${id}/remove`,{},undefined,cookie)).status,200);});
test('owner rates are versioned and do not mutate existing booking quotes',async()=>{const i=input();const b=await reserve(i);const cookie=await login();assert.equal((await post('/api/admin/rates',{cabinId:'salt',amount:50000,version:1},undefined,cookie)).status,200);assert.equal((await post('/api/admin/rates',{cabinId:'salt',amount:55000,version:1},undefined,cookie)).status,409);assert.equal((await authorizeBooking(b.id,i.accessToken)).quote.total,i.expectedTotal);assert.notEqual((await quoteStay(i)).total,i.expectedTotal);});
test('date-specific overrides apply exactly and can be removed',async()=>{const cookie=await login();const i=input();const first=await post('/api/admin/rates',{cabinId:'salt',amount:30001,version:1,start:i.checkIn,end:i.checkOut},undefined,cookie);assert.equal(first.status,200);assert.deepEqual((await quoteStay(i)).nights.map(n=>n.amount),[30001,30001,30001]);assert.equal((await post('/api/admin/rates',{cabinId:'salt',amount:null,version:2,start:i.checkIn,end:i.checkOut},undefined,cookie)).status,200);assert.equal((await quoteStay(i)).total,i.expectedTotal);});
test('CMS edits use optimistic concurrency and publish plain text',async()=>{const cookie=await login();const original=(await pool.query("SELECT * FROM documents WHERE slug='arrival'")).rows[0];const body={title:'Your arrival, calmly arranged.',eyebrow:'ARRIVAL',body:'This is safe text. <script>window.hacked=true</script> It must never execute.',version:original.version};assert.equal((await post('/api/admin/content/arrival',body,undefined,cookie)).status,200);assert.equal((await post('/api/admin/content/arrival',body,undefined,cookie)).status,409);const docs=await (await fetch(url+'/api/content')).json();assert.equal(docs.find((d:{slug:string})=>d.slug==='arrival').body,body.body);await pool.query('UPDATE documents SET title=$2,eyebrow=$3,body=$4,version=1 WHERE slug=$1',['arrival',original.title,original.eyebrow,original.body]);});
test('webhook verifies raw-body signatures before fulfillment',async()=>{const i=input();const b=await reserve(i);const oldProvider=config.provider,oldSecret=config.webhookSecret;config.provider='stripe';config.webhookSecret='whsec_tidehouse_test_fixture';try{const payload=JSON.stringify({id:'evt_signed_fixture',object:'event',type:'checkout.session.completed',livemode:false,data:{object:await sessionFor(b.id,i.accessToken)}});const bad=await fetch(url+'/api/webhooks/stripe',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':'invalid'},body:payload});assert.equal(bad.status,400);assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'holding');const signature=requireStripe().webhooks.generateTestHeaderString({payload,secret:config.webhookSecret});const good=await fetch(url+'/api/webhooks/stripe',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':signature},body:payload});assert.equal(good.status,200);assert.equal((await authorizeBooking(b.id,i.accessToken)).status,'confirmed');}finally{config.provider=oldProvider;config.webhookSecret=oldSecret;}});
