'use client';
import { useEffect, useState } from 'react';
import { api, errorMessage } from '../lib/api';
import { dateKey, displayDate, overlaps, parseDate, plusDays, today } from '../lib/pricing';
import type { CalendarEntry } from '../lib/types';
import { Icon } from './Icon';
export function AvailabilityCalendar({cabinId,onRange}:{cabinId:string;onRange?:(start:string,end:string)=>void}){
  const [month,setMonth]=useState(today().slice(0,7)+'-01');const [entries,setEntries]=useState<CalendarEntry[]|null>(null);const [start,setStart]=useState('');const [end,setEnd]=useState('');const [error,setError]=useState('');
  useEffect(()=>{let alive=true;const load=()=>api.calendar(cabinId).then(v=>{if(alive){setEntries(v);setError('');}}).catch(e=>{if(alive){setEntries(null);setError(errorMessage(e));}});setEntries(null);setStart('');setEnd('');void load();const timer=setInterval(load,15000);window.addEventListener('focus',load);window.addEventListener('tidehouse:inventory',load);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',load);window.removeEventListener('tidehouse:inventory',load);};},[cabinId]);
  const first=parseDate(month);const offset=(first.getUTCDay()+6)%7;const cells=Array.from({length:42},(_,i)=>plusDays(month,i-offset));
  const move=(n:number)=>{const date=parseDate(month);date.setUTCMonth(date.getUTCMonth()+n);setMonth(dateKey(date));};
  function choose(day:string){if(!entries)return;setError('');if(!start||end||day<=start){if(entries.some(r=>day>=r.start&&day<r.end)){setError('This arrival date is unavailable.');return;}setStart(day);setEnd('');return;}if(day<plusDays(start,2)||day>plusDays(start,21)){setError('Choose a departure 2–21 nights after arrival.');return;}if(entries.some(r=>overlaps(r,{start,end:day}))){setError('This stay crosses unavailable dates. Please choose another range.');return;}setEnd(day);onRange?.(start,day);}
  return <div className="availability-calendar"><div className="calendar-top"><h3>{first.toLocaleDateString('en-CA',{month:'long',year:'numeric',timeZone:'UTC'})}</h3><div><button type="button" className="icon-button" aria-label="Previous month" disabled={month<=today().slice(0,7)+'-01'} onClick={()=>move(-1)}><Icon name="chevron" style={{transform:'rotate(180deg)'}}/></button><button type="button" className="icon-button" aria-label="Next month" disabled={month>=plusDays(today(),365).slice(0,7)+'-01'} onClick={()=>move(1)}><Icon name="chevron"/></button></div></div><p className="calendar-instruction" aria-live="polite">{entries===null?'Checking the cabin calendar…':start&&!end?`Arrival ${displayDate(start)}. Choose your departure.`:end?`${displayDate(start)} — ${displayDate(end)} selected`:'Choose an arrival, then a departure.'}</p><div className="calendar-weekdays" aria-hidden="true">{['M','T','W','T','F','S','S'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="calendar-days">{cells.map(day=>{const outside=day.slice(0,7)!==month.slice(0,7);const unavailable=entries?.some(r=>day>=r.start&&day<r.end);const disabled=day<=today()||day>plusDays(today(),365)||entries===null;const selected=day===start||day===end;return <button type="button" key={day} disabled={disabled||outside} aria-label={`${displayDate(day,true)}${unavailable?' · unavailable':''}`} aria-pressed={selected} className={`${outside?'outside ':''}${unavailable?'unavailable ':''}${selected?'selected ':''}${start&&end&&day>start&&day<end?'in-range':''}`} onClick={()=>choose(day)}>{parseDate(day).getUTCDate()}</button>;})}</div><div className="calendar-legend"><span><i/>Available</span><span><i className="unavailable"/>Unavailable / held</span><span>2-night minimum</span></div>{error&&<p role="alert" className="form-error">{error}</p>}<p className="fine-print">Availability is checked again when you reserve. Departure dates are not charged as nights.</p></div>;
}
