'use client';
import Link from 'next/link';
import {useState} from 'react';
import {type Cabin,cabins as initialCabins} from '@/lib/catalog';
import {money} from '@/lib/domain';
import {useCatalog} from './Site';
import {FloorPlan} from './PropertyMap';
import {Modal} from './Modal';
import {Arrow} from './Brand';
export function Gallery({cabin}:{cabin:Cabin}){const [index,setIndex]=useState(0),[open,setOpen]=useState(false);return <div className="gallery"><button className="gallery-main" onClick={()=>setOpen(true)} aria-label={`Enlarge ${cabin.name} gallery photograph`}><img src={cabin.gallery[index]} alt={`${cabin.name} representative ${index===0?'architecture':index===1?'interior':'landscape'} photograph`}/><span className="gallery-count">0{index+1} / 0{cabin.gallery.length} <span>↗</span></span></button><div className="gallery-thumbs">{cabin.gallery.map((src,i)=><button key={src} onClick={()=>setIndex(i)} aria-label={`Show photograph ${i+1}`} aria-pressed={index===i}><img src={src} alt=""/></button>)}<small>Representative imagery<br/>for a fictional retreat.</small></div>{open&&<Modal title={`${cabin.name} gallery`} onClose={()=>setOpen(false)}><img className="lightbox-image" src={cabin.gallery[index]} alt={`${cabin.name} representative photograph ${index+1}`}/><div className="gallery-navigation"><button className="text-link" onClick={()=>setIndex((index+cabin.gallery.length-1)%cabin.gallery.length)}><Arrow direction="left"/>Previous</button><span>{index+1} / {cabin.gallery.length}</span><button className="text-link" onClick={()=>setIndex((index+1)%cabin.gallery.length)}>Next<Arrow/></button></div></Modal>}</div>;}
export function CabinFacts({cabin}:{cabin:Cabin}){return <><div className="cabin-facts"><div><small>YOUR PEOPLE</small><span>Up to {cabin.capacity} guests</span></div><div><small>YOUR SPACE</small><span>{cabin.area} m² interior</span></div><div><small>YOUR VIEW</small><span>{cabin.view}</span></div></div><p className="cabin-description">{cabin.description}</p><div className="amenities">{cabin.amenities.map(a=><span key={a}><i>✓</i>{a}</span>)}</div><details className="detail-disclosure"><summary>The floor plan <span>+</span></summary><FloorPlan cabin={cabin}/></details><details className="detail-disclosure"><summary>Access & getting around <span>+</span></summary><p>{cabin.access}</p><Link href="/field-notes/accessibility" className="text-link">Read the full access notes <Arrow/></Link></details>{cabin.faqs.map(f=><details className="detail-disclosure" key={f.question}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</>;}
export function CabinDetailPage({slug}:{slug:string}){const{cabins}=useCatalog(),cabin=cabins.find(c=>c.slug===slug)??initialCabins[0];return <main id="main" className="cabin-page section-pad"><Link href="/#cabins" className="back-link"><Arrow direction="left"/>All five cabins</Link><div className="section-heading"><div><span className="eyebrow">CABIN 0{cabin.id} / {cabin.view.toUpperCase()}</span><h1>{cabin.name}</h1><p className="serif-lead">{cabin.subtitle}</p></div><div className="heading-aside"><p>From {money(cabin.baseRate)} / night · CAD</p><Link className="button dark" href={`/stay?cabin=${cabin.id}`}>Find your dates <Arrow/></Link></div></div><div className="cabin-detail-layout"><Gallery cabin={cabin}/><div><CabinFacts cabin={cabin}/></div></div><div className="notice">Two nights minimum. Final cleaning, linen and parking included. Optional extras and illustrative tax are itemised before payment.</div></main>;}
export function Comparison({cabins,onClose,onChoose}:{cabins:Cabin[];onClose:()=>void;onChoose:(id:number)=>void}){return <Modal title="A little side-by-side" onClose={onClose}><h2>Find <em>your kind of quiet.</em></h2><div className="comparison-grid">{cabins.map(c=><article key={c.id}><img src={c.image} alt={`Representative photograph for ${c.name}`}/><h3>{c.name}</h3><dl><div><dt>Guests</dt><dd>Up to {c.capacity}</dd></div><div><dt>Space</dt><dd>{c.area} m²</dd></div><div><dt>Beds</dt><dd>{c.beds}</dd></div><div><dt>View</dt><dd>{c.view}</dd></div><div><dt>Base rate</dt><dd>{money(c.baseRate)} / night</dd></div></dl><p className="comparison-access">{c.access}</p><button className="button dark" onClick={()=>onChoose(c.id)}>Choose {c.name}<Arrow/></button></article>)}</div><p className="rate-note">Base rates are not a quote. Choose dates to see the complete price.</p></Modal>;}
