'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState, type ReactNode } from 'react';
import { BrandMark, Icon } from './Icon';
import { PREVIEW } from '../lib/site-config';
import { CompareProvider } from './compare';
export function Shell({children}:{children:ReactNode}) {
  const [menu,setMenu]=useState(false); const pathname=usePathname();
  useEffect(()=>setMenu(false),[pathname]);
  useEffect(()=>{ const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(false);}; window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
  return <CompareProvider><a href="#main" className="skip-link">Skip to content</a>{PREVIEW&&<div className="preview-banner">Portfolio preview <span>·</span> Sample bookings stay in this browser. No real payments. <Link href="/arrival/">About this concept ↗</Link></div>}<header className="site-header"><Link href="/" className="brand" aria-label="TIDEHOUSE home"><BrandMark/><span>TIDEHOUSE<small>A COASTAL WAY OF BEING</small></span></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/#cabins">The cabins</Link><Link href="/property/">Our little world</Link><Link href="/journal/">Field notes</Link></nav><div className="nav-actions"><Link href="/stay/" className="button button-dark nav-book">Find your stay <Icon name="diagonal" size={17}/></Link><button className="icon-button mobile-menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button></div>{menu&&<nav id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation"><Link href="/#cabins" onClick={()=>setMenu(false)}>The cabins</Link><Link href="/property/">Our little world</Link><Link href="/journal/">Field notes</Link><Link href="/accessibility/">Accessibility</Link><Link href="/arrival/">Before you arrive</Link><Link href="/stay/">Find your stay ↗</Link></nav>}</header><main id="main">{children}</main><footer className="site-footer"><div className="footer-top"><div><p className="eyebrow">A LITTLE CLOSER TO NOWHERE.</p><h2>Make room<br/>for <em>a little less.</em></h2></div><Link href="/stay/" className="round-link" aria-label="Find your stay"><Icon name="diagonal" size={34}/></Link></div><div className="footer-links"><Link href="/" className="brand"><BrandMark/><span>TIDEHOUSE<small>FIVE CABINS. ONE QUIETER COAST.</small></span></Link><nav aria-label="Footer navigation"><Link href="/accessibility/">Accessibility</Link><Link href="/arrival/">Arrival & inclusions</Link><Link href="/terms/">Booking terms</Link><Link href="/privacy/">Privacy</Link><Link href="/admin/">Owner dashboard</Link></nav></div><div className="footer-bottom"><span>© 2026 TIDEHOUSE · An independent portfolio concept.</span><span>Fictional property · Reference photography · Test payments only</span></div></footer></CompareProvider>;
}
