import type { Cabin, EditorialDocument } from './types';
export const photo = (id: string, width = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
export const imagery = {
  hero: photo('photo-1470770841072-f978cf4d019e', 2400),
  sea: photo('photo-1518837695005-2083093ee35b', 1800),
  interior: photo('photo-1449247709967-d4461a6a6103', 1400),
  bedroom: photo('photo-1505693416388-ac5ce068fe85', 1400),
  breakfast: photo('photo-1533089860892-a7c6f0a88666', 1200),
  forest: photo('photo-1441974231531-c6227db76b6e', 1400),
};
const shared = ['Natural linen bedding', 'A fully equipped kitchen', 'Private outdoor deck', 'Rain shower & botanical toiletries', 'Wi-Fi, when you need it', 'Coffee, tea & a welcome loaf'];
const commonFaqs = [
  { question: 'What is included in my stay?', answer: 'Your private cabin, linen and towels, kitchen essentials, coffee and tea, a welcome loaf, Wi-Fi, parking for one car and final cleaning. Breakfast and a private sauna session are optional; the complete price is shown before payment.' },
  { question: 'Can I bring a pet?', answer: 'This concept retreat is pet-free, apart from service animals. Please discuss any access requirements before arrival so the team can prepare your cabin.' },
  { question: 'When can we arrive?', answer: 'Check-in is from 16:00 and check-out is by 11:00. Your private arrival instructions are available with your booking confirmation. The shoreline is unlit after dark; bring a torch.' },
];
export const cabins: Cabin[] = [
  { id: 'salt', number: '01', name: 'Salt', tagline: 'Wake up with the water.', description: 'Our closest cabin to the shoreline. A quiet, timber-lined hideaway where long windows frame the water and the deck catches the first light. For two people and very few plans.', capacity: 2, beds: 'One king bed', size: 42, baseRate: 28500, view: 'Uninterrupted water view', image: photo('photo-1449158743715-0a90ebb6d2d8'), imageAlt: 'Architectural reference: a timber cabin surrounded by trees', gallery: [{src: imagery.bedroom, alt: 'Reference for a softly lit bedroom with natural linen'}, {src: imagery.interior, alt: 'Reference for a warm, carefully composed interior'}, {src: imagery.sea, alt: 'Open water and the movement of waves'}], position: [57, 64], amenities: [...shared, 'Shore-facing reading nook'], access: 'Three entrance steps; a 78 cm bathroom doorway and a stepped shower. Not a step-free cabin. The deck has a level threshold from the living space.', faqs: [{question: 'How close is Salt to the water?',answer: 'In our fictional property plan, Salt sits 40 metres from the shoreline path. The path is uneven gravel, not a paved promenade.'}, ...commonFaqs] },
  { id: 'dune', number: '02', name: 'Dune', tagline: 'A little closer to doing nothing.', description: 'Pale oak, warm plaster and a window seat made for a whole afternoon. Tucked behind the dunes, this is our most sheltered cabin, with a south-facing deck and a little more privacy.', capacity: 2, beds: 'One king bed', size: 46, baseRate: 31500, view: 'Dune & meadow view', image: photo('photo-1518780664697-55e3ad937233'), imageAlt: 'Architectural reference: a compact woodland cabin with a pitched roof', gallery: [{src: imagery.interior, alt: 'Interior reference with quiet natural materials'}, {src: imagery.bedroom, alt: 'A light-filled bedroom reference'}, {src: imagery.forest, alt: 'Dappled light through a woodland path'}], position: [39, 56], amenities: [...shared, 'South-facing sheltered deck'], access: 'Two entrance steps; a 76 cm bathroom doorway. Gravel access path. Shower has a 10 cm lip. Not a step-free cabin.', faqs: [{question: 'Is Dune private?',answer: 'The proposed dune planting screens the deck from the main path. It is the most sheltered of the five cabins.'}, ...commonFaqs] },
  { id: 'drift', number: '03', name: 'Drift', tagline: 'Room for your favourite people.', description: 'A generous table, two bedrooms and the gentle rhythm of the trees. Drift is for shared breakfasts, muddy boots by the door and stories that last long after dinner.', capacity: 4, beds: 'One king + two singles', size: 68, baseRate: 35500, view: 'Woodland & partial water view', image: photo('photo-1449844908441-8829872d2607'), imageAlt: 'Architectural reference: a thoughtfully proportioned home among trees', gallery: [{src: imagery.interior, alt: 'Reference for a shared living and dining space'}, {src: imagery.bedroom, alt: 'Bedroom furnishing reference'}, {src: imagery.forest, alt: 'Forest light on a walking trail'}], position: [32, 36], amenities: [...shared, 'Two separate bedrooms', 'A large dining table'], access: 'Four entrance steps; an 80 cm bathroom doorway. All rooms are on one floor after entry. Shower has a raised tray.', faqs: [{question: 'Are the bedrooms separate?',answer: 'Yes. The concept plan includes a king bedroom and a second bedroom with two single beds; both have a closing door.'}, ...commonFaqs] },
  { id: 'cove', number: '04', name: 'Cove', tagline: 'An open door to the coast.', description: 'Our most spacious cabin, designed around easy movement and long, unhurried mornings. Wide doors open onto a level deck, with a view that turns every cup of coffee into an occasion.', capacity: 4, beds: 'One king + two singles', size: 74, baseRate: 39500, view: 'Wide-angle coastal view', image: photo('photo-1510798831971-661eb04b3739'), imageAlt: 'Architectural reference: a contemporary cabin in a natural setting', gallery: [{src: imagery.interior, alt: 'A spacious interior reference'}, {src: imagery.bedroom, alt: 'Reference for natural bedding and warm daylight'}, {src: imagery.sea, alt: 'The shoreline and open sea'}], position: [62, 41], amenities: [...shared, 'Step-free concept layout', 'Roll-in shower', 'Two separate bedrooms'], access: 'Proposed step-free entry, 90 cm clear doorways, 150 cm turning space and roll-in shower with grab rails. These are concept design dimensions, not an audited real property. Review the floor plan and confirm individual requirements before any real-world adaptation.', faqs: [{question: 'Is Cove the accessible cabin?',answer: 'Cove is the step-free design in this fictional property. The displayed layout includes wide doorways and a roll-in shower. It is not a third-party accessibility certification.'}, ...commonFaqs] },
  { id: 'pine', number: '05', name: 'Pine', tagline: 'The quietest corner of all.', description: 'At the edge of the trees, Pine feels a world of its own. A deep reading chair, rich timber and an outdoor deck angled towards the evening light. A place to finish that book. Or start another.', capacity: 2, beds: 'One king bed', size: 48, baseRate: 33500, view: 'Pine canopy & sunset view', image: photo('photo-1470770841072-f978cf4d019e'), imageAlt: 'Landscape reference: a waterside cabin with a mountain backdrop', gallery: [{src: imagery.bedroom, alt: 'Bedroom reference with linen and warm textures'}, {src: imagery.forest, alt: 'Tall forest trees in natural light'}, {src: imagery.interior, alt: 'Interior reference for a quiet reading space'}], position: [47, 23], amenities: [...shared, 'A generous reading corner', 'Evening-light deck'], access: 'Five entrance steps on a gently sloping woodland path. Bathroom door is 77 cm wide; shower has a raised tray. Not a step-free cabin.', faqs: [{question: 'Is Pine far from the other cabins?',answer: 'Pine is approximately a three-minute walk from the welcome house in the concept property plan. The path is gravel and can be slippery in wet weather.'}, ...commonFaqs] },
];
export const addOns = [
  { id: 'breakfast' as const, title: 'A slow morning', subtitle: 'Breakfast at your door', description: 'Fresh bread, fruit, yoghurt and something warm from the oven. Delivered quietly each morning.', amount: 2400, unit: 'per guest, per night', image: imagery.breakfast },
  { id: 'sauna' as const, title: 'Warmth by the water', subtitle: 'Your private sauna hour', description: 'One private 60-minute session for your party. Towels and drinking water included; arrival team confirms the time.', amount: 8500, unit: 'per stay', image: imagery.sea },
];
export const editorial: EditorialDocument[] = [
  { slug: 'our-place', title: 'A smaller place. A slower pace.', eyebrow: 'A NOTE FROM TIDEHOUSE', body: 'Five thoughtfully made cabins, a meandering shoreline and room to hear yourself think. TIDEHOUSE is an invitation to step out of the everyday — not to fill your days, but to leave a little space in them.\n\nWe believe a good stay is made of simple things done well: natural materials, generous light, a comfortable bed and a genuinely useful guide to what is around you.', version: 1 },
  { slug: 'shoreline', title: 'Follow the shoreline.', eyebrow: 'FIELD NOTES / 01', body: 'Leave after breakfast, take the lower path and let the water set your pace. Our fictional coastal loop is a gentle 3 km wander with places to stop, sit and watch the tide.\n\nThe route includes uneven gravel, wet rocks and unprotected edges. It is not step-free. Wear sturdy shoes, keep away from the waterline in rough weather, and never use this concept guide as real navigation or tidal advice. Ask the arrival team about conditions before setting out.\n\nPack a layer, a flask and a little more time than you think you need.', version: 1 },
  { slug: 'at-the-table', title: 'Good things, close to home.', eyebrow: 'FIELD NOTES / 02', body: 'The pleasure of a small kitchen is deciding not to rush. Start with the welcome loaf, put the kettle on and make breakfast feel like part of the holiday.\n\nOur concept local guide imagines a harbour bakery, a weekly produce market and a small seasonal kitchen. No real businesses, opening times or reservations are implied. A real retreat would maintain current, verified recommendations here.\n\nChoose the optional breakfast basket when booking, or make the cabin kitchen your own. Dietary requests should be discussed before a real-world stay; the demo does not promise allergen-free preparation.', version: 1 },
  { slug: 'the-art-of-less', title: 'The art of doing a little less.', eyebrow: 'FIELD NOTES / 03', body: 'Read three pages. Watch the light move across the floor. Leave your phone in another room. Some days are better without an itinerary.\n\nA private sauna hour is the only activity you need to book here. Everything else is an invitation, not an obligation. Guests should follow the sauna operator’s health and safety guidance; the fictional experience is not a medical recommendation.\n\nThe retreat is designed around quiet hours from 22:00 to 08:00, shared paths and a little consideration for the people staying nearby.', version: 1 },
  { slug: 'arrival', title: 'Your arrival, made simple.', eyebrow: 'BEFORE YOU SET OFF', body: 'Check-in is from 16:00; check-out is by 11:00. One parking space is included per cabin. The welcome house is the first stop on the illustrated property map.\n\nA confirmed booking shows your cabin, dates, guest count, optional extras and a private management link. Keep that link safe: it allows access to your reservation and cancellation controls.\n\nTIDEHOUSE is a fictional portfolio retreat. There is no physical address to navigate to and no real accommodation to purchase. All payment-provider charges use Stripe test mode only.', version: 1 },
  { slug: 'accessibility', title: 'A stay with fewer unknowns.', eyebrow: 'ACCESSIBILITY & PRACTICAL DETAILS', body: 'Clear information is more useful than a vague promise. Each cabin page lists its entrance steps, doorway widths and shower arrangement. Cove is the proposed step-free cabin, with a 90 cm clear doorway, 150 cm turning space and roll-in shower.\n\nThe property paths are predominantly gravel. The shoreline loop is uneven, unlit and not wheelchair accessible. The sauna concept is not step-free. Service animals are welcome in the concept policy.\n\nThese are fictional design specifications, not measured or certified claims about a real property. A real launch requires an access audit and a direct way to discuss individual needs. The website supports keyboard navigation, visible focus, labelled controls and reduced motion.', version: 1 },
  { slug: 'privacy', title: 'Your details, treated carefully.', eyebrow: 'PRIVACY / DEMONSTRATION', body: 'In the PostgreSQL-backed application, your name and email are used to manage the reservation and optional confirmation email. Payment card details are entered only on Stripe’s hosted test checkout, not stored by TIDEHOUSE.\n\nA private random management token authorizes access to a booking. The server stores only its hash. Do not share your management link. Owner access is protected separately. There are no advertising or analytics cookies.\n\nThe static portfolio preview stores sample reservations in your browser only. Do not enter sensitive personal details. Photos are architectural and landscape references, not photographs of this fictional property. A real launch requires a jurisdiction-specific privacy policy, retention schedule and guest contact channel.', version: 1 },
  { slug: 'terms', title: 'The small print, plainly.', eyebrow: 'BOOKING TERMS / DEMONSTRATION', body: 'Stays are between two and twenty-one nights. Capacity includes every guest. The complete CAD quote includes accommodation, selected extras, a cleaning fee and an illustrative configured 15% tax. No real tax jurisdiction or operating business is represented.\n\nCancel at least seven days before your check-in date for a full test refund. Later cancellations receive no test refund. The same policy is saved with your reservation; refunds and cancellation progress are shown on the management page.\n\nA booking is confirmed only after the server verifies successful payment. Dates may be temporarily held during checkout. A failed or expired payment is not a confirmed stay. This website is a portfolio demonstration and does not sell real accommodation.', version: 1 },
];
export const getCabin = (id: string) => cabins.find(c => c.id === id);
export const sitePath = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH || ''}${path}`;
